// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oraculo.Models;

#nullable disable

namespace Oraculo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241011110121_Postagem-Inicial")]
    partial class PostagemInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oraculo.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoriaNome");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Oraculo.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChatId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mensagem");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("Oraculo.Models.Comunidades", b =>
                {
                    b.Property<int>("ComunidadesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComunidadesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComunidadesId"));

                    b.Property<string>("NomeComunidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeComunidade");

                    b.HasKey("ComunidadesId");

                    b.ToTable("Comunidades");
                });

            modelBuilder.Entity("Oraculo.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<string>("EventoFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventoFoto");

                    b.Property<string>("EventoTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventoTexto");

                    b.HasKey("EventoId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("Oraculo.Models.MaisComentados", b =>
                {
                    b.Property<int>("MaisComentadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaisComentadosId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaisComentadosId"));

                    b.Property<int>("PostagemId")
                        .HasColumnType("int");

                    b.HasKey("MaisComentadosId");

                    b.HasIndex("PostagemId");

                    b.ToTable("MaisComentados");
                });

            modelBuilder.Entity("Oraculo.Models.Novidade", b =>
                {
                    b.Property<int>("NovidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NovidadeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NovidadeId"));

                    b.Property<string>("NovidadeFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NovidadeFoto");

                    b.Property<string>("NovidadeTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NovidadeTexto");

                    b.HasKey("NovidadeId");

                    b.ToTable("Novidade");
                });

            modelBuilder.Entity("Oraculo.Models.Postagem", b =>
                {
                    b.Property<int>("PostagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostagemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostagemId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Compartilhamento")
                        .HasColumnType("int")
                        .HasColumnName("Compartilhamento");

                    b.Property<int>("ComunidadesId")
                        .HasColumnType("int");

                    b.Property<int>("Like")
                        .HasColumnType("int")
                        .HasColumnName("Like");

                    b.Property<int>("PostagemImg")
                        .HasColumnType("int")
                        .HasColumnName("PostagemImg");

                    b.Property<int>("PostagemNome")
                        .HasColumnType("int")
                        .HasColumnName("PostagemNome");

                    b.HasKey("PostagemId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ComunidadesId");

                    b.ToTable("Postagem");
                });

            modelBuilder.Entity("Oraculo.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("DataNascimeto")
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuarioDataNascimento");

                    b.Property<string>("UsuarioApelido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioApelido");

                    b.Property<string>("UsuarioConfirmarSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioConfirmarSenha");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioEmail");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioNome");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioSenha");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Oraculo.Models.Chat", b =>
                {
                    b.HasOne("Oraculo.Models.Categoria", "Categorias")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oraculo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Oraculo.Models.MaisComentados", b =>
                {
                    b.HasOne("Oraculo.Models.Postagem", "Postagem")
                        .WithMany()
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("Oraculo.Models.Postagem", b =>
                {
                    b.HasOne("Oraculo.Models.Categoria", "Categorias")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oraculo.Models.Comunidades", "Comunidades")
                        .WithMany()
                        .HasForeignKey("ComunidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("Comunidades");
                });
#pragma warning restore 612, 618
        }
    }
}
